# Generated by Django 5.0.7 on 2024-08-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
