# Generated by Django 5.0.7 on 2024-08-06 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_credit_eaea58_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='credit',
        ),
    ]
